### ISSUE TITLE
Extender causes forum loading to fail

### ISSUE THREAD

**Issue by luceos** [v17development/flarum-seo#51]
Error:

In case you have any extension enabled that uses the Extend class in this extension and this extension is not enabled, it will throw an unrecoverable exception.

Assumption:

I assume you are throwing this exception for issues in the past under similar circumstances.

Solution:

Use `Container::make` to get a singleton object. Core uses the same method, so in case the singleton has not yet been instantiated it will do now. The reason no Container is bound yet is because this extension wasn't booted.

**Comment by jaspervriends** [comment]
Issue is also reported via the Blog Extension https://github.com/v17development/flarum-blog/issues/53 (reminder for me to update that issue too after fixing it)

**Comment by jaspervriends** [comment]
Should be fixed in version 2.0 that will be released soon 🚀

**Comment by SKevo18** [comment]
Hi, any update on the 2.0 release? It seems that this issue is still present in the latest version of the SEO/Blog extension?
